CREATE TABLE STUDENTS_DETAILS
(
STUDENT_ID NUMBER(7),
LAST_NAME VARCHAR2(25),
FIRST_NAME VARCHAR2(25),
AGE NUMBER(4),
GENDER VARCHAR2(6),
ADDRESS VARCHAR2(25),
COURSE VARCHAR2(20),
GRADE VARCHAR2(4),
FEE_PAID NUMBER(20)
)


