create table CAR 
(
CAR_REG_NO VARCHAR2(25),
BRAND VARCHAR2(25),
MODEL VARCHAR2(20),
MODEL_YEAR NUMBER (10),
VARIANT VARCHAR2(25),
COLOR VARCHAR2(25),
YEAR_OF_PURCHASE NUMBER(5),
KILOMETERS NUMBER(10)
);


